# Generated by Django 5.2.8 on 2025-12-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_plan_stripe_product_price_id_invoicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='stripe_product_price_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
